# -*- coding: utf-8 -*-
"""week-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SanFRw6cF_2TiPbRRBoZGjyhMuhzgnFL

week-2 : data collection and clenup using python
"""

import pandas as pd
import numpy as np

sales = pd.read_csv("sales.csv")
demand = pd.read_csv("products.csv")

print("Sales Data Loaded")
print(sales.head())

print("\nProductData Loaded")
print(demand.head())

"""2. DATA CLEANING"""

# Convert date columns
sales["Order Date"] = pd.to_datetime(sales["Order Date"])
sales["Ship Date"] = pd.to_datetime(sales["Ship Date"])

# Check missing values
print("\nMissing Values in Sales")
print(sales.isnull().sum())

print("\nMissing Values in Demand")
print(demand.isnull().sum())

# Fill missing numeric values (if any)
sales.fillna(0, inplace=True)
demand.fillna(demand.mean(numeric_only=True), inplace=True)

""" 3. CALCULATED FIELDS"""

# Revenue
sales["Total Revenue"] = sales["Units Sold"] * sales["Unit Price"]

# Cost
sales["Total Cost"] = sales["Units Sold"] * sales["Unit Cost"]

# Profit
sales["Total Profit"] = sales["Total Revenue"] - sales["Total Cost"]

# Profit Margin %
sales["Profit Margin %"] = np.where(
    sales["Total Revenue"] != 0,
    (sales["Total Profit"] / sales["Total Revenue"]) * 100,
    0
)

# Discount Percentage (Demand Table)
demand["Discount %"] = (
    (demand["Base Price"] - demand["Total Price"])
    / demand["Base Price"]
) * 100

"""4. SUMMARY ANALYSIS"""

# Total Revenue by Product
product_summary = sales.groupby("Item Type")[
    ["Total Revenue", "Total Profit"]
].sum()

print("\nRevenue by Product")
print(product_summary)

# Total Revenue by Region
region_summary = sales.groupby("Region")[
    ["Total Revenue", "Total Profit"]
].sum()

print("\nRevenue by Region")
print(region_summary)

# Total Sales by Store
store_summary = demand.groupby("Store ID")[
    ["Total Price", "Units Sold"]
].sum()

print("\nStore Performance")
print(store_summary)

""" 5. SAVE CLEANED DATASETS"""

sales.to_csv("cleaned_sales.csv", index=False)
demand.to_csv("cleaned_demand.csv", index=False)

print("\n✅ Cleaned datasets saved successfully!")